# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import webserver_pb2 as webserver__pb2


class ReceiverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.receiveModel = channel.unary_unary(
                '/grpc.Receiver/receiveModel',
                request_serializer=webserver__pb2.Request.SerializeToString,
                response_deserializer=webserver__pb2.Empty.FromString,
                )


class ReceiverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def receiveModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReceiverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'receiveModel': grpc.unary_unary_rpc_method_handler(
                    servicer.receiveModel,
                    request_deserializer=webserver__pb2.Request.FromString,
                    response_serializer=webserver__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.Receiver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Receiver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def receiveModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Receiver/receiveModel',
            webserver__pb2.Request.SerializeToString,
            webserver__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
